In [1]:
import numpy as np

In [2]:
M1 = np.reshape(np.asarray([0,1,2,3,4,5,6,7]), (2,4))

In [3]:
M1 = np.reshape(np.asarray([0,1,2,3,4,5,6,7,8,9,10,11]), (3,4))

In [4]:
M2 = np.reshape(np.asarray([0,1,2,3,4,5,6,7]), (2,4))

In [5]:
print(M1)
print(M2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3]
 [4 5 6 7]]


In [6]:
print(M1 - M2)

ValueError: operands could not be broadcast together with shapes (3,4) (2,4) 

In [8]:
M2 = np.reshape(np.asarray([0,1,2,3,4,5,6,7,8,9,10,11]), (3,4))

In [9]:
print(M1 - M2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [1]:
np.reshape(np.asarray([1,1,2,2]), (1,4))

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
np.reshape(np.asarray([1,1,2,2]), (1,4))

array([[1, 1, 2, 2]])

In [4]:
list = np.reshape(np.asarray([1,1,2,2]), (1,4))

In [5]:
gt_boxes = np.reshape(np.asarray([1,1,2,2]), (1,4))

In [6]:
list = [0,1]
print(gt_boxes[list, :])

IndexError: index 1 is out of bounds for axis 0 with size 1

In [1]:
import numpy as np

anchors = np.reshape(np.asarray([0,0,1,1,0,0,2,2]), (2,4))

In [2]:
anchors

array([[0, 0, 1, 1],
       [0, 0, 2, 2]])

In [3]:
gt_boxes = np.reshape(np.asarray(0.5,0.5, 1.5,1.5), (1,4))

TypeError: asarray() takes from 1 to 3 positional arguments but 4 were given

In [4]:
gt_boxes = np.reshape(np.asarray([0.5,0.5, 1.5,1.5]), (1,4))

In [5]:
gt_boxes

array([[ 0.5,  0.5,  1.5,  1.5]])

In [6]:
a_width = anchors[:, 2] - anchors[: 0] + 1.0

ValueError: operands could not be broadcast together with shapes (2,) (0,4) 

In [7]:
a_width = anchors[:, 2] - anchors[:, 0] + 1.0

In [8]:
a_width

array([ 2.,  3.])

In [9]:
a_width = anchors[:, 2] - anchors[:, 0] + 1.0
a_height = anchors[:, 3] - anchors[:, 1] + 1.0
a_cx = anchors[:, 0] + 0.5 * a_width
a_cy = anchors[:, 1] + 0.5 * a_height

In [10]:
a_cx

array([ 1. ,  1.5])

In [11]:
gt_width = gt_boxes[:, 2] - gt_boxes[:, 0] + 1.0
gt_height = gt_boxes[:, 3] - gt_boxes[:, 1] + 1.0
gt_cx = gt_boxes[:, 0] + 0.5 * a_width
gt_cy = gt_boxes[:, 1] + 0.5 * a_height

In [13]:
gt_width

array([ 2.])

In [14]:
gt_height

array([ 2.])

In [15]:
target_dx = (gt_cx - a_cx) / a_width

In [16]:
target_dx

array([ 0.25      ,  0.16666667])

In [17]:
gt_boxes = np.reshape(np.asarray(0.5,0.5, 1.5,1.5, 0, 0, 0.5, 0.5), (2,4))

TypeError: asarray() takes from 1 to 3 positional arguments but 8 were given

In [18]:
gt_boxes = np.reshape(np.asarray([0.5,0.5, 1.5,1.5, 0, 0, 0.5, 0.5]), (2,4))

In [19]:
gt_boxes

array([[ 0.5,  0.5,  1.5,  1.5],
       [ 0. ,  0. ,  0.5,  0.5]])

In [20]:
gt_width = gt_boxes[:, 2] - gt_boxes[:, 0] + 1.0
gt_height = gt_boxes[:, 3] - gt_boxes[:, 1] + 1.0
gt_cx = gt_boxes[:, 0] + 0.5 * a_width
gt_cy = gt_boxes[:, 1] + 0.5 * a_height

In [21]:
target_dx = (gt_cx - a_cx) / a_width

In [22]:
target_dx

array([ 0.25,  0.  ])

In [23]:
gt_boxes

array([[ 0.5,  0.5,  1.5,  1.5],
       [ 0. ,  0. ,  0.5,  0.5]])

In [24]:
gt_boxes[[0,0], :]

array([[ 0.5,  0.5,  1.5,  1.5],
       [ 0.5,  0.5,  1.5,  1.5]])

In [25]:
anchors = np.random.randint(10, size=(4, 20))

In [26]:
anchors

array([[8, 8, 8, 9, 6, 7, 7, 7, 6, 4, 3, 0, 0, 3, 5, 9, 1, 8, 7, 8],
       [5, 3, 3, 1, 9, 2, 9, 4, 5, 3, 9, 0, 1, 1, 0, 9, 9, 0, 3, 5],
       [7, 3, 7, 8, 8, 9, 5, 2, 2, 0, 5, 9, 0, 7, 7, 3, 5, 8, 0, 2],
       [6, 0, 3, 3, 1, 8, 3, 5, 6, 0, 3, 3, 7, 5, 4, 1, 2, 1, 8, 9]])

In [27]:
anchors = np.random.randint(10, size=(20, 4))

In [28]:
anchors

array([[3, 3, 4, 1],
       [8, 8, 0, 6],
       [9, 1, 8, 3],
       [1, 9, 1, 8],
       [3, 4, 1, 2],
       [0, 4, 7, 5],
       [1, 2, 6, 8],
       [3, 2, 2, 0],
       [3, 4, 8, 6],
       [6, 2, 4, 6],
       [9, 4, 5, 7],
       [4, 5, 5, 9],
       [4, 9, 1, 9],
       [4, 6, 0, 3],
       [0, 4, 1, 3],
       [0, 8, 9, 1],
       [0, 3, 7, 2],
       [1, 6, 6, 3],
       [9, 7, 7, 3],
       [7, 9, 5, 3]])

In [29]:
gt_boxes = np.random.randint(5, size=(3, 4))

In [30]:
gt_boxes

array([[1, 4, 3, 0],
       [2, 3, 2, 1],
       [2, 3, 4, 0]])

In [31]:
a_width = anchors[:, 2] - anchors[:, 0] + 1.0
a_height = anchors[:, 3] - anchors[:, 1] + 1.0
a_cx = anchors[:, 0] + 0.5 * a_width
a_cy = anchors[:, 1] + 0.5 * a_height

In [32]:
gt_width = gt_boxes[:, 2] - gt_boxes[:, 0] + 1.0
gt_height = gt_boxes[:, 3] - gt_boxes[:, 1] + 1.0
gt_cx = gt_boxes[:, 0] + 0.5 * gt_width
gt_cy = gt_boxes[:, 1] + 0.5 * gt_height

ValueError: operands could not be broadcast together with shapes (3,) (20,) 

In [33]:
gt_width = gt_boxes[:, 2] - gt_boxes[:, 0] + 1.0
gt_height = gt_boxes[:, 3] - gt_boxes[:, 1] + 1.0
gt_cx = gt_boxes[:, 0] + 0.5 * gt_width
gt_cy = gt_boxes[:, 1] + 0.5 * gt_height

In [34]:
gt_cx

array([ 2.5,  2.5,  3.5])

In [35]:
target_dx = (gt_cx - a_cx) / a_width

ValueError: operands could not be broadcast together with shapes (3,) (20,) 

In [36]:
gt_cx

array([ 2.5,  2.5,  3.5])

In [37]:
a_cx

array([ 4. ,  4.5,  9. ,  1.5,  2.5,  4. ,  4. ,  3. ,  6. ,  5.5,  7.5,
        5. ,  3. ,  2.5,  1. ,  5. ,  4. ,  4. ,  8.5,  6.5])

In [38]:
anchors.argmax(axis=1)

array([2, 0, 0, 1, 1, 2, 3, 0, 2, 0, 0, 3, 1, 1, 1, 2, 2, 1, 0, 1], dtype=int64)

In [39]:
labels = [1,1,0,0,0,1,0,1]

In [40]:
labels == 1

False

In [41]:
labels = np.random.randint(1, size=(10, ))

In [42]:
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
labels = np.random.randint(2, size=(20, ))

In [52]:
labels

array([0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1])

In [53]:
inds_inside = np.random.randint(2, size=(20, ))

In [54]:
bbox_inside_weights = np.zeros((len(inds_inside), 4), dtype=np.float32)

In [55]:
bbox_inside_weights

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]], dtype=float32)

In [56]:
bbox_inside_weights[labels == 1, :]

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]], dtype=float32)

In [57]:
bbox_inside_weights[labels == 1, :] = np.array([1.,1.,1.,1.])

In [58]:
bbox_inside_weights

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.]], dtype=float32)

In [59]:
*labels.shape

SyntaxError: can't use starred expression here (<ipython-input-59-ac3bb2e75546>, line 1)

In [60]:
labels[...]

array([0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1])