In [1]:
import numpy as np

In [2]:
M1 = np.reshape(np.asarray([0,1,2,3,4,5,6,7]), (2,4))

In [3]:
M1 = np.reshape(np.asarray([0,1,2,3,4,5,6,7,8,9,10,11]), (3,4))

In [4]:
M2 = np.reshape(np.asarray([0,1,2,3,4,5,6,7]), (2,4))

In [5]:
print(M1)
print(M2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3]
 [4 5 6 7]]


In [6]:
print(M1 - M2)

ValueError: operands could not be broadcast together with shapes (3,4) (2,4) 

In [8]:
M2 = np.reshape(np.asarray([0,1,2,3,4,5,6,7,8,9,10,11]), (3,4))

In [9]:
print(M1 - M2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [1]:
np.reshape(np.asarray([1,1,2,2]), (1,4))

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
np.reshape(np.asarray([1,1,2,2]), (1,4))

array([[1, 1, 2, 2]])

In [4]:
list = np.reshape(np.asarray([1,1,2,2]), (1,4))

In [5]:
gt_boxes = np.reshape(np.asarray([1,1,2,2]), (1,4))

In [6]:
list = [0,1]
print(gt_boxes[list, :])

IndexError: index 1 is out of bounds for axis 0 with size 1

In [1]:
import numpy as np

anchors = np.reshape(np.asarray([0,0,1,1,0,0,2,2]), (2,4))

In [2]:
anchors

array([[0, 0, 1, 1],
       [0, 0, 2, 2]])

In [3]:
gt_boxes = np.reshape(np.asarray(0.5,0.5, 1.5,1.5), (1,4))

TypeError: asarray() takes from 1 to 3 positional arguments but 4 were given

In [4]:
gt_boxes = np.reshape(np.asarray([0.5,0.5, 1.5,1.5]), (1,4))

In [5]:
gt_boxes

array([[ 0.5,  0.5,  1.5,  1.5]])

In [6]:
a_width = anchors[:, 2] - anchors[: 0] + 1.0

ValueError: operands could not be broadcast together with shapes (2,) (0,4) 

In [7]:
a_width = anchors[:, 2] - anchors[:, 0] + 1.0

In [8]:
a_width

array([ 2.,  3.])

In [9]:
a_width = anchors[:, 2] - anchors[:, 0] + 1.0
a_height = anchors[:, 3] - anchors[:, 1] + 1.0
a_cx = anchors[:, 0] + 0.5 * a_width
a_cy = anchors[:, 1] + 0.5 * a_height

In [10]:
a_cx

array([ 1. ,  1.5])

In [11]:
gt_width = gt_boxes[:, 2] - gt_boxes[:, 0] + 1.0
gt_height = gt_boxes[:, 3] - gt_boxes[:, 1] + 1.0
gt_cx = gt_boxes[:, 0] + 0.5 * a_width
gt_cy = gt_boxes[:, 1] + 0.5 * a_height

In [13]:
gt_width

array([ 2.])

In [14]:
gt_height

array([ 2.])

In [15]:
target_dx = (gt_cx - a_cx) / a_width

In [16]:
target_dx

array([ 0.25      ,  0.16666667])

In [17]:
gt_boxes = np.reshape(np.asarray(0.5,0.5, 1.5,1.5, 0, 0, 0.5, 0.5), (2,4))

TypeError: asarray() takes from 1 to 3 positional arguments but 8 were given

In [18]:
gt_boxes = np.reshape(np.asarray([0.5,0.5, 1.5,1.5, 0, 0, 0.5, 0.5]), (2,4))

In [19]:
gt_boxes

array([[ 0.5,  0.5,  1.5,  1.5],
       [ 0. ,  0. ,  0.5,  0.5]])

In [20]:
gt_width = gt_boxes[:, 2] - gt_boxes[:, 0] + 1.0
gt_height = gt_boxes[:, 3] - gt_boxes[:, 1] + 1.0
gt_cx = gt_boxes[:, 0] + 0.5 * a_width
gt_cy = gt_boxes[:, 1] + 0.5 * a_height

In [21]:
target_dx = (gt_cx - a_cx) / a_width

In [22]:
target_dx

array([ 0.25,  0.  ])

In [23]:
gt_boxes

array([[ 0.5,  0.5,  1.5,  1.5],
       [ 0. ,  0. ,  0.5,  0.5]])

In [24]:
gt_boxes[[0,0], :]

array([[ 0.5,  0.5,  1.5,  1.5],
       [ 0.5,  0.5,  1.5,  1.5]])

In [25]:
anchors = np.random.randint(10, size=(4, 20))

In [26]:
anchors

array([[8, 8, 8, 9, 6, 7, 7, 7, 6, 4, 3, 0, 0, 3, 5, 9, 1, 8, 7, 8],
       [5, 3, 3, 1, 9, 2, 9, 4, 5, 3, 9, 0, 1, 1, 0, 9, 9, 0, 3, 5],
       [7, 3, 7, 8, 8, 9, 5, 2, 2, 0, 5, 9, 0, 7, 7, 3, 5, 8, 0, 2],
       [6, 0, 3, 3, 1, 8, 3, 5, 6, 0, 3, 3, 7, 5, 4, 1, 2, 1, 8, 9]])

In [27]:
anchors = np.random.randint(10, size=(20, 4))

In [28]:
anchors

array([[3, 3, 4, 1],
       [8, 8, 0, 6],
       [9, 1, 8, 3],
       [1, 9, 1, 8],
       [3, 4, 1, 2],
       [0, 4, 7, 5],
       [1, 2, 6, 8],
       [3, 2, 2, 0],
       [3, 4, 8, 6],
       [6, 2, 4, 6],
       [9, 4, 5, 7],
       [4, 5, 5, 9],
       [4, 9, 1, 9],
       [4, 6, 0, 3],
       [0, 4, 1, 3],
       [0, 8, 9, 1],
       [0, 3, 7, 2],
       [1, 6, 6, 3],
       [9, 7, 7, 3],
       [7, 9, 5, 3]])

In [29]:
gt_boxes = np.random.randint(5, size=(3, 4))

In [30]:
gt_boxes

array([[1, 4, 3, 0],
       [2, 3, 2, 1],
       [2, 3, 4, 0]])

In [31]:
a_width = anchors[:, 2] - anchors[:, 0] + 1.0
a_height = anchors[:, 3] - anchors[:, 1] + 1.0
a_cx = anchors[:, 0] + 0.5 * a_width
a_cy = anchors[:, 1] + 0.5 * a_height

In [32]:
gt_width = gt_boxes[:, 2] - gt_boxes[:, 0] + 1.0
gt_height = gt_boxes[:, 3] - gt_boxes[:, 1] + 1.0
gt_cx = gt_boxes[:, 0] + 0.5 * gt_width
gt_cy = gt_boxes[:, 1] + 0.5 * gt_height

ValueError: operands could not be broadcast together with shapes (3,) (20,) 

In [33]:
gt_width = gt_boxes[:, 2] - gt_boxes[:, 0] + 1.0
gt_height = gt_boxes[:, 3] - gt_boxes[:, 1] + 1.0
gt_cx = gt_boxes[:, 0] + 0.5 * gt_width
gt_cy = gt_boxes[:, 1] + 0.5 * gt_height

In [34]:
gt_cx

array([ 2.5,  2.5,  3.5])

In [35]:
target_dx = (gt_cx - a_cx) / a_width

ValueError: operands could not be broadcast together with shapes (3,) (20,) 

In [36]:
gt_cx

array([ 2.5,  2.5,  3.5])

In [37]:
a_cx

array([ 4. ,  4.5,  9. ,  1.5,  2.5,  4. ,  4. ,  3. ,  6. ,  5.5,  7.5,
        5. ,  3. ,  2.5,  1. ,  5. ,  4. ,  4. ,  8.5,  6.5])

In [38]:
anchors.argmax(axis=1)

array([2, 0, 0, 1, 1, 2, 3, 0, 2, 0, 0, 3, 1, 1, 1, 2, 2, 1, 0, 1], dtype=int64)

In [39]:
labels = [1,1,0,0,0,1,0,1]

In [40]:
labels == 1

False

In [41]:
labels = np.random.randint(1, size=(10, ))

In [42]:
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
labels = np.random.randint(2, size=(20, ))

In [52]:
labels

array([0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1])

In [53]:
inds_inside = np.random.randint(2, size=(20, ))

In [54]:
bbox_inside_weights = np.zeros((len(inds_inside), 4), dtype=np.float32)

In [55]:
bbox_inside_weights

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]], dtype=float32)

In [56]:
bbox_inside_weights[labels == 1, :]

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]], dtype=float32)

In [57]:
bbox_inside_weights[labels == 1, :] = np.array([1.,1.,1.,1.])

In [58]:
bbox_inside_weights

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.]], dtype=float32)

In [59]:
*labels.shape

SyntaxError: can't use starred expression here (<ipython-input-59-ac3bb2e75546>, line 1)

In [60]:
labels[...]

array([0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1])

In [1]:
import numpy as np

In [2]:
A = np.random.rand(1, 18, 14, 14)

In [3]:
print(A)

[[[[ 0.81666353  0.94975114  0.43913862 ...,  0.62892944  0.30714919
     0.72557191]
   [ 0.57013005  0.90871795  0.02086153 ...,  0.67910799  0.16136356
     0.01369628]
   [ 0.00904167  0.27881975  0.43406179 ...,  0.21471885  0.92716768
     0.3962783 ]
   ..., 
   [ 0.73330889  0.10017152  0.0812435  ...,  0.22488265  0.2079203
     0.40969509]
   [ 0.97045708  0.60685634  0.11291533 ...,  0.31252112  0.75699921
     0.05132858]
   [ 0.67719305  0.06638636  0.92541795 ...,  0.25845405  0.02780686
     0.28900992]]

  [[ 0.80188226  0.65003994  0.6514488  ...,  0.41970953  0.06171467
     0.6588547 ]
   [ 0.71690768  0.82007021  0.79329637 ...,  0.59788089  0.24411271
     0.7427932 ]
   [ 0.6109924   0.03590853  0.79722834 ...,  0.55592708  0.93437824
     0.18308626]
   ..., 
   [ 0.50124169  0.65049915  0.59356173 ...,  0.99916828  0.41188166
     0.02953434]
   [ 0.53286342  0.80100958  0.95203108 ...,  0.51313604  0.1415146
     0.5811162 ]
   [ 0.50878375  0.26841234  0.94742

In [4]:
print(A.shape)

(1, 18, 14, 14)


In [5]:
print(A[:, 9, :, :])

[[[ 0.89270616  0.31196482  0.63725305  0.81300127  0.40261288  0.13369573
    0.25072603  0.02494425  0.76498698  0.00354713  0.3484799   0.38687061
    0.54330122  0.89541359]
  [ 0.52462474  0.99371649  0.43015672  0.4855429   0.68163574  0.27652197
    0.83162949  0.757136    0.78589808  0.49152046  0.56654545  0.89801526
    0.69734746  0.84517579]
  [ 0.36501849  0.34170651  0.79630611  0.33542183  0.88153124  0.22311459
    0.22136604  0.4990484   0.28010603  0.19101288  0.00177319  0.49712236
    0.98926649  0.30324028]
  [ 0.55735276  0.8648342   0.74687697  0.49441741  0.12597852  0.28161238
    0.89438765  0.71236734  0.70207166  0.72003611  0.18546375  0.23665154
    0.16463757  0.10429498]
  [ 0.11458812  0.92918215  0.44723816  0.97900824  0.5955667   0.70564306
    0.64047336  0.03720601  0.179974    0.94595523  0.39511027  0.23254694
    0.6367032   0.17103693]
  [ 0.60981004  0.29667831  0.87735922  0.4232792   0.83383172  0.16762619
    0.87136373  0.79484488  0.98619

In [6]:
print(A[:, 9, :, :].shape)

(1, 14, 14)


In [7]:
A = np.random.rand(2,4)

In [8]:
print(A[:,2].shape)

(2,)


In [9]:
print(A[:,2])

[ 0.31672262  0.93833877]


In [10]:
print(A
    )

[[ 0.18428705  0.15297798  0.31672262  0.72918344]
 [ 0.66283347  0.86112212  0.93833877  0.27408094]]


In [11]:
A = np.random.randint(18, 14, 14)

ValueError: low >= high

In [12]:
A = np.random.randint(0, 2, size=(18, 14, 14))

In [13]:
print(A
    )

[[[1 0 1 ..., 1 0 0]
  [0 0 1 ..., 1 0 1]
  [0 1 1 ..., 1 1 1]
  ..., 
  [1 1 0 ..., 1 0 1]
  [0 1 0 ..., 0 1 1]
  [1 1 1 ..., 1 1 0]]

 [[1 1 1 ..., 1 1 0]
  [0 1 1 ..., 0 1 0]
  [0 1 1 ..., 1 1 0]
  ..., 
  [0 1 1 ..., 1 1 0]
  [0 1 1 ..., 0 1 1]
  [0 1 1 ..., 1 1 1]]

 [[0 0 0 ..., 0 1 1]
  [1 0 0 ..., 0 0 0]
  [1 0 0 ..., 0 1 0]
  ..., 
  [0 1 0 ..., 1 1 1]
  [1 0 1 ..., 1 0 1]
  [1 0 1 ..., 1 0 0]]

 ..., 
 [[0 0 1 ..., 1 1 1]
  [1 0 0 ..., 1 0 0]
  [1 0 1 ..., 1 0 0]
  ..., 
  [1 0 1 ..., 1 0 0]
  [0 0 0 ..., 1 0 0]
  [0 0 0 ..., 1 0 0]]

 [[1 0 1 ..., 1 0 1]
  [1 1 1 ..., 0 0 0]
  [1 0 0 ..., 0 0 0]
  ..., 
  [1 1 1 ..., 0 1 0]
  [0 0 0 ..., 1 0 0]
  [0 0 0 ..., 1 1 0]]

 [[1 1 1 ..., 0 0 0]
  [1 1 1 ..., 1 1 0]
  [1 1 0 ..., 1 0 1]
  ..., 
  [0 0 0 ..., 1 0 0]
  [0 1 1 ..., 1 1 0]
  [0 1 1 ..., 1 0 1]]]


In [14]:
print(A[9, :, :])

[[1 0 1 0 0 0 1 1 1 1 0 0 0 1]
 [1 1 0 1 0 1 1 1 1 1 0 0 1 1]
 [0 0 0 0 1 0 1 1 0 0 0 1 0 1]
 [0 0 1 1 0 0 0 1 1 1 0 0 1 0]
 [1 1 0 0 1 0 0 0 1 0 0 0 0 1]
 [0 0 0 0 1 1 0 1 0 0 0 0 1 0]
 [0 0 1 1 1 1 0 0 1 0 1 1 1 0]
 [0 1 0 0 1 1 1 0 1 1 0 1 1 0]
 [1 1 1 0 0 1 1 0 0 0 1 1 1 1]
 [1 1 0 1 1 1 0 1 1 1 1 1 1 1]
 [1 1 0 1 0 0 1 0 1 0 0 0 0 1]
 [1 0 0 0 1 0 1 0 1 0 0 1 1 0]
 [0 1 0 0 1 1 0 1 0 1 1 0 1 1]
 [0 1 0 1 0 1 0 1 1 0 1 1 0 0]]


In [15]:
print(A[9:, :, :].shape)

(9, 14, 14)


In [16]:
A = np.random.rand(1,18, 14, 14)

In [17]:
print(A[:, 9:, :, :].shape)

(1, 9, 14, 14)
